const menuButton=document.querySelector('[data-menu]');
const nav=document.querySelector('[data-nav]');
menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));nav.classList.toggle('is-open',!open)});
nav?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{menuButton?.setAttribute('aria-expanded','false');nav.classList.remove('is-open')}));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const countObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const el=entry.target;const target=Number(el.dataset.count);if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){el.textContent=target;return}const start=performance.now();const duration=900;const tick=now=>{const progress=Math.min((now-start)/duration,1);el.textContent=Math.round(target*(1-Math.pow(1-progress,3)));if(progress<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);countObserver.unobserve(el)}),{threshold:.7});
document.querySelectorAll('[data-count]').forEach(el=>countObserver.observe(el));
const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
document.querySelectorAll('[data-case-detail]').forEach(detail=>{const videos=[...detail.querySelectorAll('video')];if(!videos.length)return;const syncVideos=()=>videos.forEach(video=>{if(detail.open&&!reduceMotion){video.play().catch(()=>{})}else{video.pause()}});detail.addEventListener('toggle',syncVideos);syncVideos()});
