const menuButton=document.querySelector('[data-menu]');
const nav=document.querySelector('[data-nav]');
const workMenu=document.querySelector('[data-work-menu]');
const workTrigger=document.querySelector('[data-work-trigger]');
const closeWorkMenu=()=>{workMenu?.classList.remove('is-open');workTrigger?.setAttribute('aria-expanded','false')};
const alignHashTarget=hash=>{const target=document.querySelector(hash);if(!target)return;const headerHeight=document.querySelector('[data-header]')?.offsetHeight||0;const top=target.getBoundingClientRect().top+window.scrollY-headerHeight;window.scrollTo({top,behavior:'auto'})};
menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));nav.classList.toggle('is-open',!open)});
workTrigger?.addEventListener('click',()=>{const open=workTrigger.getAttribute('aria-expanded')==='true';workMenu.classList.toggle('is-open',!open);workTrigger.setAttribute('aria-expanded',String(!open))});
nav?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{menuButton?.setAttribute('aria-expanded','false');nav.classList.remove('is-open');closeWorkMenu()}));
document.querySelectorAll('[data-work-submenu] a,.project-divider-title a').forEach(link=>link.addEventListener('click',()=>[350,1100].forEach(delay=>window.setTimeout(()=>alignHashTarget(link.hash),delay))));
window.addEventListener('load',()=>{if(window.location.hash)[350,1100,2200].forEach(delay=>window.setTimeout(()=>alignHashTarget(window.location.hash),delay))});
document.addEventListener('click',event=>{if(!workMenu?.contains(event.target))closeWorkMenu()});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeWorkMenu();menuButton?.setAttribute('aria-expanded','false');nav?.classList.remove('is-open')}});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px -5%'});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const motionButton=document.querySelector('[data-motion-toggle]');
const motionMedia=[...document.querySelectorAll('[data-motion],[data-detail-motion]')];
const setMotionState=paused=>{document.body.classList.toggle('motion-paused',paused);motionMedia.forEach(media=>{const detail=media.closest('[data-project-detail]');paused||(detail&&!detail.open)?media.pause():media.play().catch(()=>{})});if(!motionButton)return;motionButton.setAttribute('aria-pressed',String(paused));motionButton.innerHTML=paused?'<span aria-hidden="true">▶</span> Play motion':'<span aria-hidden="true">Ⅱ</span> Pause motion'};
motionButton?.addEventListener('click',()=>setMotionState(motionButton.getAttribute('aria-pressed')!=='true'));
if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)setMotionState(true);
document.querySelectorAll('[data-project-detail]').forEach(detail=>detail.addEventListener('toggle',()=>setMotionState(document.body.classList.contains('motion-paused'))));
